### ISSUE TITLE
Be able to opt in and out of certain notification types. 

### ISSUE THREAD

**Issue by kbuczynski-nashpl** [whitep4nth3r/pantherworld#102]
Atm the notification system is too noisy, I would like to be able to opt out of certain events if I can.

**Comment by whitep4nth3r** [comment]
Questions:

- where would you like to opt out of notifications?
- [ ] front end
- [ ] discord
- [ ] stream overlay
- [ ] twitch chat

???

**Comment by kbuczynski-nashpl** [comment]
Front End 🙏 

I dont think it is feasible to do discord, stream overlay and twitch as these are more global ones ment for everyone
