### ISSUE TITLE
Let Robin Hood join the game

### ISSUE THREAD

**Issue by Gramok** [whitep4nth3r/pantherworld#108]
The rich getting richer, the poor getting poorer. So let's introduce someone to the game who can change this - Robin Hood!

Stealing from the rich (top wealth players) and gifting it to the poor (poorest players who played the game in the last X days).

Robin joins the game randomly (once every X days), takes some high rarity items from the wealthiest players and gifts them automatically to the poorest ones active in the game.

**Comment by whitep4nth3r** [comment]
Kind of a duplicate of https://github.com/whitep4nth3r/pantherworld/issues/34
