### ISSUE TITLE
Improvement to the header Menu

### ISSUE THREAD

**Issue by MhemedAbderrahmen** [whitep4nth3r/pantherworld#109]
The menu button is kind of weird now, well it works fine but I suggest some improvements.

Whenever you click on it you get this huge container on top of everything and it hides whatever you have on the screen.
The issue is that it only closes whenever you click again on the Icon which to me is not very intuitive so maybe add that if you click outside of it it hides as well. 

![image](https://github.com/user-attachments/assets/0ff9c784-d93b-4c05-86f8-f7ca51596aaa)

**Comment by whitep4nth3r** [comment]
Fixed by https://github.com/whitep4nth3r/pantherworld/commit/e0d1e4c9282ebf136daa36c2e537014c6137312a
