### ISSUE TITLE
Suggestion: Full Leaderboard and Player Lookup for the website

### ISSUE THREAD

**Issue by manniL** [whitep4nth3r/pantherworld#14]
At the moment, the leaderboard is limited to the top three.
It'd be great to have more info on that, such as:

* A full leaderboard with pagination
* A player detail page with inventory, when last active and maybe even a history of "actions taken" (move/pickup/...) 😋

**Comment by whitep4nth3r** [comment]
✅ Leaderboard

**Comment by whitep4nth3r** [comment]
Closing as done.
