### ISSUE TITLE
Spawned shows "NaN Days Ago" after login

### ISSUE THREAD

**Issue by Gramok** [whitep4nth3r/pantherworld#15]
Hi,

just started playing on Twitch and after login with Twitch on https://p4nth3r.world/ it shows "NaN Days Ago" in the "Spawned" area. See attached screenshot

<img width="770" alt="bug" src="https://github.com/user-attachments/assets/5e0777ba-e789-43b2-8c45-c7c5ab583ab0">

Switching zones in Twitch chat didn't help.

Twitch Name is @DeGramok

**Comment by Gramok** [comment]
@whitep4nth3r just logged out and did a re-login. Now it changed to "Unavailable".

**Comment by whitep4nth3r** [comment]
Ok that's better but it should say "earlier today"! I'm gonna have another look.

**Comment by whitep4nth3r** [comment]
cc @manniL

**Comment by whitep4nth3r** [comment]
The issue is in the back end and a `createdAt` field is not available (I HATE NOSQL).

Referenced: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/issues/147
