### ISSUE TITLE
issue: Inventory header on the homepage wraps onto second line and breaks alignment

### ISSUE THREAD

**Issue by danielphilipjohnson** [whitep4nth3r/pantherworld#24]
Inventory header wraps onto second line and breaks alignment

<img width="833" alt="image" src="https://github.com/user-attachments/assets/fe124ad0-da8d-446d-b2a6-dcca69520f72">

## Proposed solution

For now make the div a flexbox and justify the content with space between

```html
<div class="flex flex-col justify-between">
```

Now it looks like the following
<img width="700" alt="image" src="https://github.com/user-attachments/assets/f83a9a68-e5c2-46eb-ad57-c3e560095157">

## Alternative solution 
Use flex 1 on the inventory item

<img width="798" alt="image" src="https://github.com/user-attachments/assets/c2c8a887-b17c-4d71-a241-008fa02b2515">

**Comment by whitep4nth3r** [comment]
Fixed in https://github.com/whitep4nth3r/pantherworld/commit/a840a481c7dabbc367d4ab37defb647be3b8ca8c
