### ISSUE TITLE
Unable to claim item Ancient book

### ISSUE THREAD

**Issue by JoshLuedeman** [whitep4nth3r/pantherworld#27]
An ancient book spawned in the desert zone but when I went to claim it, it didn't work. This just happened minutes ago if you need to review logs. Here is a screenshot
![image](https://github.com/user-attachments/assets/577367c8-876d-425d-a1cb-2d45b3357b2e)

**Comment by whitep4nth3r** [comment]
Josh, you were too late. You only have 60 seconds to claim.

**Comment by JoshLuedeman** [comment]
I thought I was right there when it appeared. Sorry
