### ISSUE TITLE
[feat] !move takes time

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/pantherworld#49]
Depending on what zone you're trying to move from and to.
Limit !moves for people with certain wealth tax and over?

**Comment by brettbrooks** [comment]
Could the move delay take into account the number of items the user has, kind of like a weight so slower movement. That means people with less items have more chance, which will go down as they collect more and more.

**Comment by whitep4nth3r** [comment]
Implemented here: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/169

A 1000ms delay per 250 items in an inventory has been applied.
We can edit this number easily.
