### ISSUE TITLE
Suggestion: Join date/user number on profile/inventory page

### ISSUE THREAD

**Issue by jschuur** [whitep4nth3r/pantherworld#5]
Show the user's join date and sequential user # on their inventory page.

Goal: People love to know/talk about how early they joined a thing.

**Comment by whitep4nth3r** [comment]
Partially done.

Players can now see "X days ago spawned" on inventory.

Player sequential number would be good BUT:

We'd need to do either of these on the backend:

1. Migrate all players to have a sequential number, save sequential number on insert to DB
2. Calculate sequential number when making API call to /world/inventory (which could end up being "expensive")

**Comment by whitep4nth3r** [comment]
Too overwhelming to think about this right now.
