### ISSUE TITLE
UI improvements for /leaderboard

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/pantherworld#61]
There are some small presentation issues present on the leaderboard when viewing on a small screen/mobile.

In particular:

- Icon spills out of button on small screens
- Table columns shift width when clicking on sort headers

**Comment by yoshivb** [comment]
@whitep4nth3r Would we want to keep the design as is atm with unsorted columns not having any icon or would we prefer them to have an unsorted icon?

**Comment by whitep4nth3r** [comment]
I would say no icon for unsorted columns? Might get a bit crowded.
