### ISSUE TITLE
[item] add legumes & spices

### ISSUE THREAD

**Issue by matthewbrandt** [whitep4nth3r/pantherworld#64]
spices (suggested rarity 200-240):
- cinnamon
- cumin
- turmeric
- ginger
- paprika
- black pepper
- cardamom
- clove
- nutmeg
- coriander

legumes (suggested rarity 600-900):
- lentils
- chickpeas
- black beans
- kidney beans
- pinto beans
- lima beans
- green peas
- soybeans

**Comment by whitep4nth3r** [comment]
Completed in https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/167
