### ISSUE TITLE
[feat] player command to see what's lying around in a zone

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/pantherworld#70]
If a player is curious they can !scan a zone to see what is lying around. 

No claiming though, just a report.

Maybe the scan command won't find all. 

@username scanned the area and found...

---

Maybe don't be explicit in what has been dropped, but give hints?

Dropped items can currently be picked up at any time. It's just a case of finding out what's there somehow.

**Comment by whitep4nth3r** [comment]
Could add categories to items.
e.g. !scan vegetable will tell you if there are any vegetables lying around in your current zone.

**Comment by whitep4nth3r** [comment]
e.g.

command:
`!scan beach`

response:
`Currently unclaimed on the beach: some shells, a few plants, and something precious.`

**Comment by whitep4nth3r** [comment]
Will be more effective if paired with https://github.com/whitep4nth3r/pantherworld/issues/73

**Comment by ricardodevries** [comment]
> command: `!scan beach`

There should be a cool down on this command per user.

**Comment by whitep4nth3r** [comment]
Consider adding to player model:

`lastScan`: Date

**Comment by whitep4nth3r** [comment]
Initial MVP: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/174

Todo

[ ] Limit scanning per players?
[ ] Send event over websocket

**Comment by whitep4nth3r** [comment]
New bug: 
<img width="678" alt="image" src="https://github.com/user-attachments/assets/1a7cb366-6b5a-49b7-b003-564f432c4d88">

**Comment by whitep4nth3r** [comment]
Latest bug fixed here: https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/commit/6afd4bfabcdb1a2f8c06e08dc65f7bbd5e10169f
