### ISSUE TITLE
VIPs advantage

### ISSUE THREAD

**Issue by aDevPanda** [whitep4nth3r/pantherworld#79]
Channel VIPs have a significant advantage as they are not restricted by twitch's no identical messages in 30 seconds anti spam feature.

**Comment by whitep4nth3r** [comment]
This will be solved by the following features:

https://github.com/whitep4nth3r/pantherworld/issues/78
https://github.com/whitep4nth3r/pantherworld/issues/49

**Comment by whitep4nth3r** [comment]
✅ !move limits implemented

**Comment by whitep4nth3r** [comment]
Closed as will address further in: https://github.com/whitep4nth3r/pantherworld/issues/78
