### ISSUE TITLE
[bug] Ranked on the leaderboard despite having an empty inventory.

### ISSUE THREAD

**Issue by ricardodevries** [whitep4nth3r/pantherworld#85]
I have a empty inventory:

![image](https://github.com/user-attachments/assets/39af4568-30fc-4666-b435-b89cc1280569)

but I am still on the leaderboard with 3 items worth 261 wealth:

![image](https://github.com/user-attachments/assets/6c04d24f-117b-4e48-8aee-fadf3455c53a)

This might be related to #83.

**Comment by whitep4nth3r** [comment]
Fixed in https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/pull/172
