### ISSUE TITLE
[bug] Wealth index difference

### ISSUE THREAD

**Issue by ricardodevries** [whitep4nth3r/pantherworld#89]
The wealth index between the inventory and the leaderboard is different:

![image](https://github.com/user-attachments/assets/c7a41462-379d-4742-9914-dabb9e3b663e)
![image](https://github.com/user-attachments/assets/c45988d1-e2fc-467a-8b7b-cea2bbde7bb1)

**Comment by ricardodevries** [comment]
This might not be related to the above but despite no inventory, it still takes 12ms to travel:

![image](https://github.com/user-attachments/assets/7bb78a7b-16c7-40e9-b176-23d0e7c4bec3)

**Comment by whitep4nth3r** [comment]
I think they're probably related.
