### ISSUE TITLE
[bug] !cook with lots of ingredients fails

### ISSUE THREAD

**Issue by ricardodevries** [whitep4nth3r/pantherworld#90]
I used the command `!cook red lentils + garlic bulb + fresh red chilli + fresh coriander + fresh ginger + turmeric root + cumin seeds + cardamom pods + whole nutmeg + sea salt` and that resulted in a error. See Sentry for more information: https://the-claw.sentry.io/share/issue/c37317dbc6874179a899dbd74343ad68/.

**Comment by whitep4nth3r** [comment]
Fixed in https://github.com/whitep4nth3r/p4nth3rb0t-mainframe/commit/777fdcfd82e9e653aa1cf2063520950e9edb3c8d

(Ginger didn't have a flavour)
