### ISSUE TITLE
Limit number of !move commands

### ISSUE THREAD

**Issue by Gramok** [whitep4nth3r/pantherworld#91]
Moving around the world is exhausting. You should be reminded to get some rest before you collapse.

Therefore, after a certain amount of !move commands during a defined period of time, the player must rest for a certain amount of time.

"You walked too much, get some rest!"

More items, more rest is needed.

**Comment by whitep4nth3r** [comment]
Closed as duplicate of: https://github.com/whitep4nth3r/pantherworld/issues/78
